---
all:
  hosts:
    vpn1:
      ansible_host: vpn1.home.phaezer.io
    pve1:
      ansible_host: pve1.dc0.plsr.io
    pve2:
      ansible_host: pve2.dc0.plsr.io
    pve3:
      ansible_host: pve3.dc0.plsr.io
    opn1:
      ansible_host: opn1.dc0.plsr.io
    opn2:
      ansible_host: opn2.dc0.plsr.io
      # vpn2:
      #   ansible_host: vpn2.home.phaezer.io
  children:
    vpn:
      hosts:
        vpn1:
    proxmox:
      hosts:
        pve1:
        pve2:
        pve3:
    firewall:
      hosts:
        opn1:
        opn2:
# vpn2:
